### ISSUE TITLE
lodash.isequal does not provide an export named 'default'

### ISSUE THREAD

**Issue by jhubbardsf** [vadimkorr/svelte-carousel#97]
Trying to get Svelte-Carousel working in my SvelteKit application. Currently running into some issues. I have svelte-carousel installed as a devDependency. This is my svelte.config file.

```
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),
		vite: {
			plugins: [WindiCSS.default()],
			vite: {
				optimizeDeps: {
					include: ['lodash.get', 'lodash.isequal', 'lodash.clonedeep']
				}
			}
		}
	}
};
```

I created a carousel/index.svelte file with the following contents

```
<script>
  import { onMount } from 'svelte';

  let Carousel; // for saving Carousel component class
  let carousel; // for calling methods of the carousel instance
  onMount(async () => {
    const module = await import('svelte-carousel');
    Carousel = module.default;
  });

  const handleNextClick = () => {
    carousel.goToNext()
  }
</script>

<svelte:component
  this={Carousel}
  bind:this={carousel}
>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</svelte:component>

<button on:click={handleNextClick}>Next</button>
```

I get the following error when I try to go to the page.
<img width="467" alt="Screen Shot 2022-02-25 at 4 15 02 PM" src="https://user-images.githubusercontent.com/2974948/155804137-4aed7cc1-93bf-46bb-b5d2-6d083e960e46.png">

**Comment by aditiakusuma** [comment]
maybe you must put  the config like this ` 

      const config = {
	      kit: {
		      adapter: adapter(),
		      vite: {
			      optimizeDeps: {
				      include: ['lodash.get', 'lodash.isequal', 'lodash.clonedeep']
			      },
			      // plugins: [myPlugin]
		      }
	      },
      };

 `

**Comment by vadimkorr** [comment]
Resolved

**Comment by lxk1170** [comment]
Adding the svelte.config.js gives me this error:
```invalid export in /Users/x/Projects/svelte-demo/myapp/svelte.config.js```
I took out the adapter, is it necessary?

**Comment by kinxiel** [comment]
Still getting the same error.

`requested module '/node_modules/.pnpm/lodash.isequal@4.5.0/node_modules/lodash.isequal/index.js?v=467393be' does not provide an export named 'default'`

Not sure where I should put the settings. I placed them both in `vite.config.ts` and `svelte.config.js`, but still get the error.

`svelte.config.js`

```js
import sveltePreprocess from "svelte-preprocess";
import preprocess from "svelte-preprocess";
import adapter from "@sveltejs/adapter-auto";

export default {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: sveltePreprocess(),
  preprocess: [
    preprocess({
      postcss: true,
    }),
  ],

  kit: {
    adapter: adapter(),
    vite: {
      optimizeDeps: {
        include: ["lodash.get", "lodash.isequal", "lodash.clonedeep"],
      },
    },
  },
};

```

`vite.config.ts`

```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
  optimizeDeps: {
    include: ['lodash.get', 'lodash.isequal', 'lodash.clonedeep']
  }
})

```

Please let me know if I am doing something wrong. Thanks
